### ISSUE TITLE
Move logos to a proper CDN because EPITA websites always break?

### ISSUE THREAD

**Issue by utybo** [Epidocs/epita.it#32]
*Today, on "EPITA's websites are broken"*

![image](https://user-images.githubusercontent.com/5175705/67906283-61607400-fb74-11e9-83eb-3f8650c0fa1a.png)

This subsequently breaks the icon in EPITA.it

![image](https://user-images.githubusercontent.com/5175705/67906308-6d4c3600-fb74-11e9-92c2-a9ea826e3b6d.png)

Of course, this is just a temporary outage, but it might be worthwhile to consider moving all logos to a separate CDN because of how often the websites break.

I could see potential copyright or trademark issues with hosting those on a separate CDN though, but it would increase the reliability (and probably loading speed) of epita.it.

**Comment by matiboux** [comment]
The policy and current position of EPITA.it on the matter is **not to store** any "additional information" than what's required for the service.

> The data stored by EPITA.it for each service we're offering a link to is restricted to the minimum information
> — https://epita.it/legal

Also, this behavior was thought through even before the project was released. This is supposed to act like a **status indicator for the website** the tile is inking to.

In the scenario of a locked website, like epita.fr was, the browser is not asking the user for a password and is just getting its request rejected. So this was working as intended on EPITA.it's end.

Priorities should be on finding or designing background materials for the tiles lacking one. A CDN or a local host or those would sometimes be necessary. That's the case for "EPITA ALED".

Finally, like you said, for copyright or trademark issues, "official" background material should not be hosted by EPITA.it or a partner provider.

**Comment by utybo** [comment]
Understandable, though I disagree that a logo should be a *status indicator* for a website. A missing logo will just cause useless requests from the client that could possibly hang forever (until it hits a instead of cleanly failing with some error code directly. But whatever.

**Comment by matiboux** [comment]
A request to a missing logo will just be stalled and will eventually time out. Unless a careless user tweaked their developer settings, it shouldn't be an issue.

Major and worst issues would arise if the centralized host of all the background materials would go down.

By the way, a logo *should not* be a status indicator, but this behavior was thought through and it simply works like it. It's not an official feature and this shouldn't be relied on.

One way to fix properly display that behavior would be to load all images using javascript and display them only when loading is a success, a status error otherwise. This would be a struggle and would be some useless scripting for the client.
